import numpy as np
arr = np.array([[1, 2], [4, 5], [7, 8]])
print("Original array:")
print(arr)
print("Type of array:", type(arr))
print("Shape of array:", arr.shape)
print("Size of array:", arr.size)
print("Dimensions of array:", arr.ndim)
print("Data type of array:", arr.dtype)
print("Indexing the array(0,1):", arr[0:1])
arr2 = np.array([[20, 21], [22, 23]])
con = np.concatenate((arr, arr2), axis=0)
print("Concatenated array:")
print(con)