import pandas as pd
print("Reading iris dataset...")
col_names = ['SepalLength', 'SepalWidth', 'PetalLength', 'PetalWidth', 'Species']
iris_data = pd.read_csv('D:\\Clg\\Clg_Programs\\2nd Sem\\Ds\\iris.csv', header=1, names=col_names)
print(iris_data)
print(iris_data[['SepalLength', 'SepalWidth']])
print(iris_data.iloc[3],'\n\n',iris_data.iloc[4])
print("\nFirst 3 rows of the dataset:", iris_data.head(3))
print("\n\nData Shape:", iris_data.shape)
print("\n\nData info:\n", iris_data.info())
print("\nDescriptive Statistics:\n", iris_data.describe())
print("Sum of SepalLength:", iris_data['SepalLength'].sum())
print("Maximum of SepalLength:", iris_data['SepalLength'].max())
print("Mean of SepalLength:", iris_data['SepalLength'].mean())
print("Median of SepalLength:", iris_data['SepalLength'].median())
print("Mode of SepalLength:", iris_data['SepalLength'].mode()[0])   