import pandas as pd
import numpy as np
from scipy.stats import skew, kurtosis
print("Reading data from diabetes dataset...")
path_1 = "C:\\Users\\Admin\\Desktop\\Kittyboy\\Clg_Programs\\2nd Sem\\Ds\\diabetes.csv"
path_2 = "C:\\Users\\Admin\\Desktop\\Kittyboy\\Clg_Programs\\2nd Sem\\Ds\\1.csv"
dia1 = pd.read_csv(path_1)
dia2 = pd.read_csv(path_2)
print(dia1)
print(dia2)
print("Description of diabetes dataset 1 :")
print(dia1.describe())
print("Description of diabetes dataset 2 :")
print(dia2.describe())
x = input("Enter column name:")
print("Average")
print(dia1[x].mean(),'\t', dia2[x].mean())
print("Median")
print(dia1[x].median(),'\t', dia2[x].median())
print("Mode")
print(dia1[x].mode()[0],'\t', dia2[x].mode())
print("Variance")
print(dia1[x].var(),'\t', dia2[x].var())
print("Standard Deviation")
print(dia1[x].std(),'\t', dia2[x].std())
print("Frequency")
print(dia1[x].value_counts(),'\t', dia2.value_counts())
print("Skewness")
print(skew(dia1[x]),'\t', skew(dia2[x]))
print("Kurtosis")
print(kurtosis(dia1[x]),'\t', kurtosis(dia2[x]))